"""Defines the fixed-order feature vector used by the classical ML skin
tone classifier, built from the color statistics produced by
skin_segmentation.masked_color_stats. Kept as a single source of truth so
the training script and the live inference path can never drift apart.

Feature set chosen by cross-validated experiment (see
scripts/experiment_feature_selection.py), not by default/guesswork: since
this project's labels were generated by binning images on measured Lab
lightness (L), L/a/b medians are the direct signal the labels came from.
The other 15 stats (std-devs, HSV, YCrCb) turned out to add noise rather
than signal on this dataset's 37 training samples — cross-validated exact
accuracy went from 57% (all 18 features) to 95% (just these 3). If you
retrain on a meaningfully larger dataset, re-run that experiment script —
the best feature set can change once there's enough data for extra
features to pay for themselves.
"""

FEATURE_NAMES = [
    "L_med",
    "a_med",
    "b_med",
]


def to_vector(stats: dict) -> list[float]:
    """Converts a masked_color_stats() dict into a fixed-order feature
    vector matching FEATURE_NAMES."""
    return [stats[name] for name in FEATURE_NAMES]
