"""Phase 9 — Model training (classical ML, adapted).

The project spec calls for a MobileNetV2/EfficientNetB0 transfer-learning
CNN. That needs TensorFlow or PyTorch, which requires an internet
connection to install — not available in this environment. This script
instead trains a classical ML classifier (Gradient Boosting) on a
3-feature color vector (L/a/b medians) defined in app/services/features.py,
using only the already-available numpy/OpenCV/scikit-learn stack.

This is a legitimate, defensible choice for a 45-image dataset: a
high-capacity CNN would badly overfit data this small regardless of which
framework trains it. The feature set itself was chosen by cross-validated
experiment, not by default (see scripts/experiment_feature_selection.py):
since labels were generated by binning images on measured L, the L/a/b
medians are the direct signal the labels came from, and the other 15
color-statistics (std-devs, hue, YCrCb) turned out to add noise rather
than signal on 37 training samples — cross-validated exact accuracy went
from 57% (18 features, Random Forest) to 95% (3 features, Gradient
Boosting). Gradient Boosting with shallow trees was chosen over Random
Forest specifically because it fits low-dimensional, mostly-monotonic
thresholds (which is what this 3-feature problem is) more precisely than
an averaged ensemble of deeper trees.

See train_cnn_mobilenetv2.py for the documented upgrade path once a larger
dataset and a TensorFlow-capable machine (or Colab) are available.
"""

import csv
import json
import sys
from pathlib import Path

import joblib
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix, f1_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

BACKEND_ROOT = Path(__file__).resolve().parent.parent / "backend"
sys.path.insert(0, str(BACKEND_ROOT))

from app.services.features import FEATURE_NAMES  # noqa: E402

LABELS_CSV = Path(__file__).resolve().parent.parent / "dataset_processed" / "labels.csv"
MODEL_OUT_DIR = BACKEND_ROOT / "trained_models"
CLASS_ORDER = ["very_fair", "fair", "light", "medium", "olive", "tan", "brown", "deep"]


def extract_features_for_split(split: str):
    """Reads precomputed feature values from labels.csv rather than
    re-running segmentation on the already-cropped patch images.

    This matters, not just for speed: the crops in dataset/<split>/<class>/
    are tight, near-uniform-color patches. Re-running GrabCut on a crop
    that's already almost entirely skin removes the background contrast
    GrabCut needs to find a foreground boundary, and can fail outright on
    some images. The feature values computed once, during labeling in
    prepare_dataset.py (on the original full photo, before cropping), are
    the correct and only source of truth here.
    """
    X, y, files = [], [], []
    with open(LABELS_CSV, newline="") as f:
        for row in csv.DictReader(f):
            if row["split"] != split:
                continue
            X.append([float(row[name]) for name in FEATURE_NAMES])
            y.append(row["class_id"])
            files.append(row["crop_file"])
    return np.array(X), np.array(y), files


def main():
    print("Extracting features...")
    X_train, y_train, _ = extract_features_for_split("train")
    X_val, y_val, _ = extract_features_for_split("validation")
    X_test, y_test, files_test = extract_features_for_split("test")
    print(f"  train: {X_train.shape}, validation: {X_val.shape}, test: {X_test.shape}")

    # With this little data per class, a held-out validation set alone is
    # too noisy to trust for model selection, so we also run stratified
    # k-fold cross-validation over train+validation combined as the primary
    # evaluation signal, and report the held-out test set as a secondary,
    # small-sample check.
    X_trainval = np.vstack([X_train, X_val])
    y_trainval = np.concatenate([y_train, y_val])

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("gb", GradientBoostingClassifier(
            n_estimators=150,
            max_depth=2,
            random_state=42,
        )),
    ])

    n_splits = min(4, min(np.bincount(np.unique(y_trainval, return_inverse=True)[1])))
    n_splits = max(2, n_splits)
    print(f"\nRunning {n_splits}-fold stratified cross-validation on train+validation ({len(y_trainval)} samples)...")
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
    cv_preds = cross_val_predict(pipeline, X_trainval, y_trainval, cv=skf)

    print("\n=== Cross-validation results (train+validation) ===")
    print(classification_report(y_trainval, cv_preds, labels=CLASS_ORDER, zero_division=0))
    macro_f1 = f1_score(y_trainval, cv_preds, labels=CLASS_ORDER, average="macro", zero_division=0)
    weighted_f1 = f1_score(y_trainval, cv_preds, labels=CLASS_ORDER, average="weighted", zero_division=0)
    print(f"Macro F1: {macro_f1:.3f}  Weighted F1: {weighted_f1:.3f}")

    cm = confusion_matrix(y_trainval, cv_preds, labels=CLASS_ORDER)
    print("\nConfusion matrix (rows=true, cols=predicted), order:", CLASS_ORDER)
    print(cm)

    # The 8 classes are ordinal (points on a lightness continuum), so a
    # prediction of the immediately adjacent class (e.g. true=olive,
    # pred=light) is a materially smaller error than a prediction far away
    # on the scale (e.g. true=olive, pred=very_fair). Off-by-one accuracy
    # makes that distinction visible instead of treating every miss the
    # same way plain accuracy does.
    class_index = {c: i for i, c in enumerate(CLASS_ORDER)}
    true_idx = np.array([class_index[c] for c in y_trainval])
    pred_idx = np.array([class_index[c] for c in cv_preds])
    off_by_one_acc = float((np.abs(true_idx - pred_idx) <= 1).mean())
    exact_acc = float((true_idx == pred_idx).mean())
    print(f"\nExact-class accuracy (CV): {exact_acc:.2f}")
    print(f"Off-by-one accuracy (CV, adjacent class counts as correct): {off_by_one_acc:.2f}")

    # Fit final model on all train+validation data.
    pipeline.fit(X_trainval, y_trainval)

    print("\n=== Held-out test set (very small sample — read as a sanity check only) ===")
    if len(y_test) > 0:
        test_preds = pipeline.predict(X_test)
        for fname, true_label, pred_label in zip(files_test, y_test, test_preds):
            mark = "OK" if true_label == pred_label else "MISS"
            print(f"  [{mark}] {fname}: true={true_label} pred={pred_label}")
        test_acc = (test_preds == y_test).mean()
        print(f"Test accuracy: {test_acc:.2f} ({(test_preds == y_test).sum()}/{len(y_test)})")

    # Save model bundle.
    MODEL_OUT_DIR.mkdir(parents=True, exist_ok=True)
    bundle = {
        "pipeline": pipeline,
        "class_order": CLASS_ORDER,
        "feature_names": FEATURE_NAMES,
    }
    model_path = MODEL_OUT_DIR / "skin_tone_model.joblib"
    joblib.dump(bundle, model_path)
    print(f"\nSaved model to {model_path}")

    with open(MODEL_OUT_DIR / "class_names.json", "w") as f:
        json.dump(CLASS_ORDER, f, indent=2)

    metrics_summary = {
        "method": "GradientBoostingClassifier (max_depth=2) on 3-dim [L_med, a_med, b_med] feature vector",
        "cv_folds": n_splits,
        "cv_macro_f1": round(macro_f1, 3),
        "cv_weighted_f1": round(weighted_f1, 3),
        "cv_exact_accuracy": round(exact_acc, 3),
        "cv_off_by_one_accuracy": round(off_by_one_acc, 3),
        "n_train": int(len(y_train)),
        "n_validation": int(len(y_val)),
        "n_test": int(len(y_test)),
        "test_accuracy": round(float((pipeline.predict(X_test) == y_test).mean()), 3) if len(y_test) else None,
        "confusion_matrix_labels": CLASS_ORDER,
        "confusion_matrix": cm.tolist(),
    }
    with open(MODEL_OUT_DIR / "training_metrics.json", "w") as f:
        json.dump(metrics_summary, f, indent=2)
    print(f"Saved metrics to {MODEL_OUT_DIR / 'training_metrics.json'}")


if __name__ == "__main__":
    main()
